import os

from dotenv import load_dotenv

load_dotenv()

TOKEN = os.getenv('DISCORD_TOKEN')
WIZARD_ROLE = int(os.getenv('WIZARD_ROLE'))
VERSION = os.getenv('BOT_VERSION')
UPDATE_LOCATION = os.getenv('BOT_UPDATE_LOCATION')
GENIUS_API_TOKEN = os.getenv('GENIUS_API_TOKEN')
ENABLE_CUSTOM_COMMANDS_MALWARE_SCANNING = os.getenv('ENABLE_CUSTOM_COMMANDS_MALWARE_SCANNING')
CUSTOM_COMMANDS_MAX_EXECUTION_TIME = int(os.getenv('CUSTOM_COMMANDS_MAX_EXECUTION_TIME'))
VIRUSTOTAL_API_KEY = os.getenv('VIRUSTOTAL_API_KEY')
